"""NFL stadium coordinates: where each point came from, and how far it is from the venue.

THE PROBLEM THIS SOLVES. No NFL feed this project trusts carries stadium coordinates, and
nfldata's `airports.csv` is an AIRPORT - a plausible point that is not the point. So the
coordinates are sourced here, per venue, with provenance on every one:

  * `nfl_stadiums.csv` (committed, hand-written) maps each nflverse (stadium_id, stadium
    name) PAIR to a Wikidata item. The pair and not the id, because the id alone is wrong:
    nflverse files a 2026 Jaguars home game at Tottenham under `JAX00`, the Jacksonville
    id, so an id-keyed lookup would fetch Florida's weather for a game in London.
  * `nfl_stadium_points.csv` (committed, GENERATED by `research/nfl_stadium_coords.py`)
    carries the Wikidata coordinate (P625, CC0) and its measured offset from the venue:
    the distance to the OpenStreetMap footprint of the object tagged with the SAME
    Wikidata id, 0.0 when the point lies inside it. OSM is the verifier only; the point
    used is Wikidata's, because OSM is ODbL and a derived coordinate would carry its
    share-alike terms onto anything published from it.

A venue with no measured offset is NOT used. An unstated offset is the failure this whole
module exists to prevent, so absence refuses rather than falls back.

ROOFS. The structure (`roof_type`: open_air | fixed | retractable) is a property of the
venue; nflverse's per-game `roof` (outdoors | open | closed | dome | '') is a property of
the game. They disagree - nflverse labels the 2026 Munich, Paris and Melbourne games
`dome`, and the same Allianz Arena was `outdoors` under `GER00` in 2022 and 2024 - so
`playing_conditions()` answers 1 only when both say the pitch is open to the sky, 0 only
when both say it is covered, and None (unknown) on any disagreement or missing state.
"""
import csv
import math
import os
from datetime import datetime
from zoneinfo import ZoneInfo

HERE = os.path.dirname(os.path.abspath(__file__))
CROSSWALK = os.path.join(HERE, "nfl_stadiums.csv")
POINTS = os.path.join(HERE, "nfl_stadium_points.csv")

ROOF_TYPES = ("open_air", "fixed", "retractable")
ET = ZoneInfo("America/New_York")      # nflverse `gametime` is US/Eastern, always
EARTH_KM = 6371.0088

# The source of every coordinate, as it is written onto a weather row.
COORD_SOURCE = "wikidata:P625"


def load_crosswalk(path=CROSSWALK):
    """{(stadium_id, nflverse_name): {qid, roof_type, roof_source}}. Refuses a duplicate
    pair or an unknown roof type rather than keeping the last one."""
    out = {}
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            key = (r["stadium_id"], r["nflverse_name"])
            if key in out:
                raise ValueError(f"crosswalk lists {key} twice")
            if r["roof_type"] not in ROOF_TYPES:
                raise ValueError(f"{key}: roof_type {r['roof_type']!r} not in {ROOF_TYPES}")
            out[key] = {"qid": r["wikidata_qid"], "roof_type": r["roof_type"],
                        "roof_source": r["roof_source"]}
    return out


def load_points(path=POINTS):
    """{qid: point row}. Numeric columns parsed; an empty offset stays None."""
    if not os.path.exists(path):
        return {}
    out = {}
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            row = dict(r)
            for c in ("latitude", "longitude", "precision_deg", "offset_km",
                      "centroid_km"):
                row[c] = float(r[c]) if r.get(c) not in (None, "") else None
            row["inside_footprint"] = (None if r.get("inside_footprint") in (None, "")
                                       else int(r["inside_footprint"]))
            out[r["qid"]] = row
    return out


def venue_id(qid):
    """The integer `venue_id` a weather row carries: the Wikidata item number."""
    if not qid or not qid.startswith("Q") or not qid[1:].isdigit():
        raise ValueError(f"not a Wikidata item id: {qid!r}")
    return int(qid[1:])


def resolve(stadium_id, name, crosswalk, points):
    """(venue dict, None) or (None, reason). Never a guess: an unmapped pair, a venue with
    no coordinate and a coordinate with no measured offset are all refusals."""
    m = crosswalk.get((stadium_id, name))
    if m is None:
        return None, "pair_not_in_crosswalk"
    p = points.get(m["qid"])
    if p is None or p["latitude"] is None or p["longitude"] is None:
        return None, "no_coordinate"
    if p["offset_km"] is None:
        return None, "offset_not_measured"
    return {"venue_id": venue_id(m["qid"]), "qid": m["qid"], "name": p.get("label") or name,
            "latitude": p["latitude"], "longitude": p["longitude"],
            "offset_km": p["offset_km"], "roof_type": m["roof_type"]}, None


def playing_conditions(roof_type, nflverse_roof):
    """1 if an outdoor reading describes the playing conditions, 0 if it does not, None if
    that is not known. Agreement is required for either answer."""
    g = (nflverse_roof or "").strip().lower()
    if roof_type == "open_air":
        return 1 if g == "outdoors" else None
    if roof_type == "retractable":
        return {"open": 1, "closed": 0}.get(g)
    if roof_type == "fixed":
        return 0 if g in ("dome", "closed") else None
    raise ValueError(f"roof_type {roof_type!r}")


def kickoff_ts(gameday, gametime):
    """nflverse gameday + gametime, US/Eastern, as UTC seconds. None if either is absent."""
    if not gameday or not gametime:
        return None
    return datetime.strptime(f"{gameday} {gametime}", "%Y-%m-%d %H:%M").replace(
        tzinfo=ET).timestamp()


# ---------------------------------------------------------------------------
# geometry - small, local, and enough for distances of a few kilometres
# ---------------------------------------------------------------------------

def haversine_km(lat1, lon1, lat2, lon2):
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp, dl = p2 - p1, math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * EARTH_KM * math.asin(math.sqrt(a))


def _project(lat0, lon0, lat, lon):
    """Equirectangular km about (lat0, lon0). Error is negligible at stadium scale."""
    x = math.radians(lon - lon0) * math.cos(math.radians(lat0)) * EARTH_KM
    y = math.radians(lat - lat0) * EARTH_KM
    return x, y


def point_in_ring(lat, lon, ring):
    """Ray casting over a ring of (lat, lon)."""
    inside = False
    n = len(ring)
    for i in range(n):
        (ya, xa), (yb, xb) = ring[i], ring[(i + 1) % n]
        if (ya > lat) != (yb > lat):
            x = xa + (lat - ya) * (xb - xa) / (yb - ya)
            if lon < x:
                inside = not inside
    return inside


def distance_to_ring_km(lat, lon, ring):
    """Distance from the point to the nearest edge of the ring, in km."""
    best = math.inf
    pts = [_project(lat, lon, a, b) for a, b in ring]
    for i in range(len(pts)):
        (x1, y1), (x2, y2) = pts[i], pts[(i + 1) % len(pts)]
        dx, dy = x2 - x1, y2 - y1
        t = 0.0 if dx == dy == 0 else max(0.0, min(1.0, -(x1 * dx + y1 * dy) / (dx * dx + dy * dy)))
        best = min(best, math.hypot(x1 + t * dx, y1 + t * dy))
    return best


def ring_centroid(ring):
    """Area-weighted centroid (lat, lon) of a ring; vertex mean if degenerate."""
    lat0, lon0 = ring[0]
    pts = [_project(lat0, lon0, a, b) for a, b in ring]
    a2 = cx = cy = 0.0
    for i in range(len(pts)):
        (x1, y1), (x2, y2) = pts[i], pts[(i + 1) % len(pts)]
        c = x1 * y2 - x2 * y1
        a2 += c
        cx += (x1 + x2) * c
        cy += (y1 + y2) * c
    if abs(a2) < 1e-12:
        return (sum(a for a, _ in ring) / len(ring), sum(b for _, b in ring) / len(ring))
    cx, cy = cx / (3 * a2), cy / (3 * a2)
    lat = lat0 + math.degrees(cy / EARTH_KM)
    lon = lon0 + math.degrees(cx / (EARTH_KM * math.cos(math.radians(lat0))))
    return lat, lon


def footprint_offset(lat, lon, rings):
    """(inside, offset_km, centroid_km) of a point against a footprint of one or more
    outer rings. offset is 0.0 inside, else the distance to the nearest edge; centroid_km
    is the distance to the centroid of the ring that is nearest."""
    if not rings:
        raise ValueError("no footprint rings")
    scored = []
    for ring in rings:
        inside = point_in_ring(lat, lon, ring)
        d = 0.0 if inside else distance_to_ring_km(lat, lon, ring)
        scored.append((d, inside, ring))
    d, inside, ring = min(scored, key=lambda s: s[0])
    clat, clon = ring_centroid(ring)
    return inside, d, haversine_km(lat, lon, clat, clon)
